### ISSUE TITLE
关于fh5900v的一些问题请教

### ISSUE THREAD

**Issue by abszse** [kyvli/hackintosh-asus-fh5900v#1]
您好，我的电脑也是fh5900v，配置相同的情况下，昨天晚上进行装黑苹果时，直接成功（用了您的引导文件），进入系统设置之后，一切正常，三个小时左右，无法开机，提示acpi错误，我在各个地方爬楼寻找发现您已经将config文件改成对应的了，故想询问如何解决？（本人小白，如有冒犯，多有得罪）

**Comment by kyvli** [comment]
进入bios，调整DVMT-prealloc这个值，之前64m的可以调成32m，之前32m的可以调成64m，试一下

**Comment by abszse** [comment]
尝试了一下32m/64m/128m，32m/64m均报错acpi错误，128m无报错，但仍然无法进入，并且没有明显的错误代码
这个是改为128m的图片，有点懵
![QQ图片20200326120754](https://user-images.githubusercontent.com/46434033/77609252-76420780-6f5a-11ea-995f-fed4390f0e45.jpg)

**Comment by kyvli** [comment]
图上我也看不出啥，确定 efi/clover里面的东西都没有动是吧？要不晚上我再把我的配置发你一份试试，最近有做了一些调整，applealc驱动仿冒等，或者去远景论坛里问问

**Comment by abszse** [comment]
都没动，害，麻烦再发一份，谢谢了

**Comment by kyvli** [comment]
更新了，你试试

**Comment by kyvli** [comment]
对了，我的macos版本是10.15.3

**Comment by abszse** [comment]
不好意思 一直没看到您的回复 之前应该是我插错口了…  换成usb2.0成功安装 然后用了论坛您上传的驱动 目前已经正常 十分感谢
